<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>Tutorial: Model Evaluation and Deployment</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-introduction" class="section level2">
<h2>Introduction</h2>
<p>A key challenge in an analytics project after creating a model is to figure out what to do with it. How will we use it to solve the business problem? What should we recommend the business do? In asking these questions we have moved from the domain of predictive analytics— the subject of the last module—to the domain of <em>prescriptive</em> analytics, which is focused on making (to quote DSB) “actionable recommendations based on a data analytic model about what the decision-maker should do to achieve a particular objective.” This prescriptive aim <em>roughly</em> lines up with the final phases of the CRISP-DM analytics process, Model Evaluation and Model Deployment. I say “roughly” because prescriptive analytics could take place during the CRISP-DM Modeling phase and because deployment can mean a variety of things in analytics projects. A model might be deployed by writing a report explaining a key relationship in the data and recommending a course of action, which is clearly prescriptive. Or it might be deployed by being put into production—for example, implementing a model to automatically forecast a KPI. This is not clearly prescriptive. Nevertheless, I would argue that a key feature of any analytics solution should include a prescriptive component, a recommendation for how the analytic results should be used—which course of action, out of the many available, should be taken.</p>
<!-- Prescriptive analytics is often discussed narrowly as model-based optimization:  using outputs from a predictive model as inputs to a secondary model of a quantity to be maximized, such as profit. But I think prescriptive analytics can be usefully regarded more broadly as any use of quantitative results to make a recommendation.  -->
<p>Consequently, <em>translation</em> and <em>persuasion</em> are key activities in these later phases of the analytics process. We must translate model results into, and persuade an audience of stakeholders about, recommended actions. This is not simple. It requires that the analyst venture beyond quantifiable inputs and outputs into less certain domains, ones that require weighing possibilities, exercising business judgment, and making an argument for the best course of action—your considered recommendation.</p>
<p>This tutorial will walk you through that process.</p>
</div>
<div id="section-preparation" class="section level2">
<h2>Preparation</h2>
<p>Here is the consolidated code developed in the last tutorial for cleaning the data, fitting a tree model using all predictors, and computing performance metrics.</p>
<pre class="r"><code># Load packages
library(tidyverse)
library(janitor)
library(rpart)
library(rpart.plot)


# Import and clean data
d &lt;- read_csv(&quot;megatelco.csv&quot;) %&gt;%
  clean_names() %&gt;% 
  mutate(reported_satisfaction = factor(reported_satisfaction,
                                        levels = c(&quot;very_unsat&quot;,&quot;unsat&quot;,&quot;avg&quot;, &quot;sat&quot;, &quot;very_sat&quot;),
                                        ordered = T),
         reported_usage_level = factor(reported_usage_level,
                                       levels = c(&quot;very_little&quot;, &quot;little&quot;, &quot;avg&quot;, &quot;high&quot;, &quot;very_high&quot;),
                                       ordered = T),
         considering_change_of_plan = factor(considering_change_of_plan,
                                       levels = c(&quot;no&quot;, &quot;never_thought&quot;, &quot;perhaps&quot;, &quot;considering&quot;, &quot;actively_looking_into_it&quot;),
                                       ordered = T),
         leave = factor(leave),
         college = recode_factor(college, &quot;one&quot; = &quot;yes&quot;, &quot;zero&quot; = &quot;no&quot;)) %&gt;% 
  filter(income &gt; 0,
         house &gt; 0,
         handset_price &lt; 1000,
         !is.na(over_15mins_calls_per_month)) 


# Fit tree
(tree_model &lt;- rpart(leave ~ ., data = select(d, -id)))</code></pre>
<pre><code>## n= 4994 
## 
## node), split, n, loss, yval, (yprob)
##       * denotes terminal node
## 
##  1) root 4994 2468 STAY (0.4941930 0.5058070)  
##    2) house&lt; 600490 3306 1364 LEAVE (0.5874168 0.4125832)  
##      4) overage&gt;=97.5 1074  218 LEAVE (0.7970205 0.2029795) *
##      5) overage&lt; 97.5 2232 1086 STAY (0.4865591 0.5134409)  
##       10) leftover&gt;=24.5 743  281 LEAVE (0.6218035 0.3781965) *
##       11) leftover&lt; 24.5 1489  624 STAY (0.4190732 0.5809268)  
##         22) leftover&lt; 2.5 733  341 LEAVE (0.5347885 0.4652115) *
##         23) leftover&gt;=2.5 756  232 STAY (0.3068783 0.6931217) *
##    3) house&gt;=600490 1688  526 STAY (0.3116114 0.6883886)  
##      6) income&gt;=99826 570  245 LEAVE (0.5701754 0.4298246)  
##       12) overage&gt;=54.5 299   79 LEAVE (0.7357860 0.2642140) *
##       13) overage&lt; 54.5 271  105 STAY (0.3874539 0.6125461) *
##      7) income&lt; 99826 1118  201 STAY (0.1797853 0.8202147) *</code></pre>
<pre class="r"><code># Confusion matrix
table(predicted = predict(tree_model, type = &quot;class&quot;),
      observed = d$leave) </code></pre>
<pre><code>##          observed
## predicted LEAVE STAY
##     LEAVE  1930  919
##     STAY    538 1607</code></pre>
<pre class="r"><code># Accuracy
sum(d$leave == predict(tree_model, type = &quot;class&quot;)) / nrow(d)</code></pre>
<pre><code>## [1] 0.7082499</code></pre>
</div>
<div id="section-business-validation" class="section level2">
<h2>Business Validation</h2>
<p>We evaluated the tree model using accuracy, a simple classifier performance metric. But while accuracy allows us to compare models— for example, the tree model is clearly better than our first model that consisted in predicting with the majority class—it can’t answer the larger, and more important, question of whether this model performance suffices for solving the business problem. At this point we need to do business validation of the model and approach, by checking to make sure that the analytic work we’ve done solves the initial business problem. It is not untypical for a project to drift, such that the solution no longer fits the problem. Or, sometimes, we need to redefine the problem in light of the available data and analytics.</p>
<p>So what was the problem? DSB re-describes it in Chapter 11.</p>
<blockquote>
<p>Why is churn a problem? Because it causes us to lose money. The real business problem is losing money. If a customer actually were costly to us rather than profitable we may not mind losing her. We would like to limit the amount of money we are losing— not simply to keep the most customers. Therefore, we want to take the value of the customer into account. Our expected value framework helps us to frame that analysis. (284)</p>
</blockquote>
<p>The business problem is not churn but the amount of money the company is losing due to churn. We will discuss the expected value framework but will first review probability and model evaluation using the profit metric.</p>
</div>
<div id="section-probability" class="section level2">
<h2>Probability</h2>
<p>In the tutorial for the last module we used a tree model of <code>leave</code> to predict a class label: <code>STAY</code> or <code>LEAVE.</code> The predicted class label was defined as the majority class in each leaf node of the tree. So, for example, if the majority of customers in a node—say, 6 out of 10—had an observed outcome of <code>STAY</code> then the model would predict <code>STAY</code> for those customers and for future similar customers. But it would be easy enough to translate 6/10 into a probability rather than a class label. The probability in this case would be a rate derived from the counts in that leaf node: 6/10 represents a probability of .6 that customers in that node would stay. Translating counts into probabilities in this way makes a tree classification model flexible and powerful.</p>
<p>In this sense, probability is simply an observed rate of event occurrence in historical data. It can be thought of as a proportion representing that rate, a number ranging between 0 and 1, with 0 indicating the impossibility of the event and 1 indicating the certainty of the event. A probability of .5 represents uncertainty—a coin toss.</p>
<p>When working with small samples probabilities of 0 and 1 tend to occur by chance, when in reality probabilities are really never 0 or 1. To avoid this unrealistic result, we use what is known as the Laplace correction:</p>
<p><span class="math display">\[p(c) = \frac{n + 1}{n+m+2}\]</span> where <span class="math inline">\(n\)</span> is the number of examples in the leaf belonging to class <span class="math inline">\(c\)</span>, and <span class="math inline">\(m\)</span> is the number of examples not belonging to class <span class="math inline">\(c\)</span>.</p>
<div id="section-predicting-probabilities" class="section level3">
<h3>Predicting probabilities</h3>
<p>In the last module we used the<code>predict()</code> function to extract predicted class labels from the model. For example:</p>
<div class="tutorial-exercise" data-label="predict" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Predict class label
predict(tree_model, type = &quot;class&quot;) %&gt;%
  head</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>However, we can easily obtain a <em>probability</em> for leaving or staying, calculated as described above, by changing the <code>type</code> argument to “prob”:</p>
<div class="tutorial-exercise" data-label="predict-prob1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Predict probability -- produces two columns
predict(tree_model, type = &quot;prob&quot;) %&gt;%
  head</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Notice that some of the probabilities seem to be repeated (for example, observations 3-5) and that the probability of <code>LEAVE</code> (in column 1) plus the probability of <code>STAY</code> (in column 2) always equals 1.</p>
<ol style="list-style-type: decimal">
<li><p>Probabilities are repeated because some observations wind up in the same leaf node, and therefore share the same rate of event occurrence.</p></li>
<li><p>Staying and leaving are mutually exclusive events, since for a given customer one or the other <em>must</em> occur. Thus <span class="math inline">\(p(STAY) + p(LEAVE) = 1\)</span>, which means that <span class="math inline">\(p(STAY) = 1- p(LEAVE)\)</span> and <span class="math inline">\(p(LEAVE) = 1- p(STAY)\)</span>.</p></li>
</ol>
<p>Formally, when using a model to estimate the probability of staying (or leaving) we are actually estimating that probability given some predictors, <span class="math inline">\(p(STAY | X)\)</span>. This can be read as: the probability of staying given or conditional upon (that is what “|” means) a set of predictors, <span class="math inline">\(X\)</span>.</p>
</div>
</div>
<div id="section-confusion-matrix" class="section level2">
<h2>Confusion Matrix</h2>
<p>Recall that the confusion matrix summarizes model performance by tallying instances where the predictions are correct—true positives (TP) and true negatives (TN)—and instances where the predictions are incorrect—false positives (FP) and false negatives (FN):</p>
<pre><code>##          observed
## predicted LEAVE STAY
##     LEAVE TP    FP  
##     STAY  FN    TN</code></pre>
<p>Here is the confusion matrix with actual counts:</p>
<div class="tutorial-exercise" data-label="tab" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>table(predicted = d$leave,
      observed = predict(tree_model, type = &quot;class&quot;))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>When we use a tree model to predict a class label (<code>type = &quot;class&quot;</code>), as here, we are implicitly using a probability threshold of .5. Recall that the tree uses the majority class in a given leaf node to model observations in that node. The majority represents a proportion of observations greater than .5, and this proportion, as we’ve noted, is the estimated probability for the node. But there is nothing magic about the .5 probability threshold for classifying observations. We could easily have used a different threshold, and using different thresholds produces different sorts of model errors in the resulting confusion matrices.</p>
<p>First, notice that we can obtain exactly the same confusion matrix as the one above by using a probability threshold of .5 as the class cutoff. The code says: if the predicted probability is greater than .5 then predict <code>LEAVE</code>, otherwise predict <code>STAY</code>.</p>
<div class="tutorial-exercise" data-label="tab2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>table(predicted = ifelse(predict(tree_model, type = &quot;prob&quot;)[,1] &gt; .5, &quot;LEAVE&quot;, &quot;STAY&quot;),
      observed = d$leave)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>What would happen if we used a threshold of, say, .7? This would make it harder for a leaf node to receive a class label of <code>LEAVE</code> since 7 out of 10 observations in a leaf node would need to be <code>LEAVE</code>. The model’s predictions of <code>LEAVE</code> should therefore go down.</p>
<div class="tutorial-exercise" data-label="tab3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>table(predicted = ifelse(predict(tree_model, type = &quot;prob&quot;)[,1] &gt; .7, &quot;LEAVE&quot;, &quot;STAY&quot;),
      observed = d$leave)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>And they do. This illustrates a general point: we can manipulate the class probability threshold to change the <em>sorts</em> of errors a model makes. Business validation of a model involves setting the threshold in a way that, for a particular business problem, maximizes benefits and minimizes costs.</p>
</div>
<div id="section-profit" class="section level2">
<h2>Profit</h2>
<p>Let’s get specific about costs and benefits in the MegaTelCo case by supposing that, for purposes of illustration, the incentive proposed by Marketing will cost the company 200 dollars and that retained customers will produce additional revenue of 800 dollars in the next year. (This is a guess. In reality we don’t know what additional revenue would be since customers likely have different plans.) Profit for retained customers would thus be 800 - 200 = 600 dollars. Here is the cost-benefit matrix:</p>
<pre><code>##          observed
## predicted LEAVE STAY
##     LEAVE   600 -200
##     STAY      0    0</code></pre>
<p>True positives are a benefit because those customers, having been correctly identified by the model, are candidates for targeting; they can be convinced to renew. False positives are a cost because these customers were already going to stay; the incentive will be wasted on them. Moreover, costs and benefits will only be considered for customers predicted to leave—the first row of the table— since they are the only ones to whom the incentive will be offered. To calculate profit we simply multiply the dollar value in each cell by the corresponding number in the confusion matrix. Notice that, as a consequence, profit will be relative to the cost matrix and the probability threshold used to create a given confusion matrix. We can calculate profit at the default threshold by multiplying the two tables together. (Note that this is NOT “matrix multiplication” in the linear algebraic sense, but simply a convenient way of multiplying values in the cells.)</p>
<pre class="r"><code># Confusion matrix
table(predicted = predict(tree_model, type = &quot;class&quot;),
      observed = d$leave)</code></pre>
<pre><code>##          observed
## predicted LEAVE STAY
##     LEAVE  1930  919
##     STAY    538 1607</code></pre>
<pre class="r"><code># Cost-benefit matrix
cost_benefit</code></pre>
<pre><code>##          observed
## predicted LEAVE STAY
##     LEAVE   600 -200
##     STAY      0    0</code></pre>
<pre class="r"><code># Profit matrix
table(predicted = predict(tree_model, type = &quot;class&quot;),
      observed = d$leave) * 
  cost_benefit</code></pre>
<pre><code>##          observed
## predicted   LEAVE    STAY
##     LEAVE 1158000 -183800
##     STAY        0       0</code></pre>
<p>Profit in this case is positive: 974,200. Let’s do the same sort of calculation using the probability threshold of .7. Does profit go up or down?</p>
<pre class="r"><code># Profit matrix
table(predicted = ifelse(predict(tree_model, type = &quot;prob&quot;)[,1] &gt; .7, &quot;LEAVE&quot;, &quot;STAY&quot;),
      observed = d$leave) *
  cost_benefit</code></pre>
<pre><code>##          observed
## predicted  LEAVE   STAY
##     LEAVE 645600 -59400
##     STAY       0      0</code></pre>
<p>Profit went down: 586,200.</p>
<div id="section-profit-curve" class="section level3">
<h3>Profit Curve</h3>
<p>A profit curve displays the estimated profit associated with a confusion matrix at every possible probability threshold for a given cost matrix. Profit curves are useful for comparing classifiers and for determining what proportion of customers should be targeted with an offer in order to maximize profit. Figure 8-2 in DSB is an example:</p>
<p><img src="images/profit_curve.png" /></p>
<p>The x-axis in this plot represents subsets of customers arranged from highest to lowest predicted probability (or “score”). The profit curve essentially visualizes what happens to profit when different probability thresholds are used to decide whether to extend an offer. Because the data is sorted on the probability score, those probability thresholds correspond to different proportions of customers. Here is how DSB summarizes it:</p>
<blockquote>
<p>We can produce a list of instances in the predicted scores, ranked by decreasing score, and then measure the expected profit that would result from choosing each successive cut-point in the list. Conceptually this amounts to ranking the list of instances by score from highest to lowest and sweeping down through it, recording the expected profit after each instance. At each cut-point we record the percentage of the list predicted as positive and the corresponding estimated profit. Graphing these values gives us a profit curve. (212)</p>
</blockquote>
<p>We will use a profit curve below.</p>
</div>
</div>
<div id="section-expected-benefit-framework" class="section level2">
<h2>Expected Benefit Framework</h2>
<p>DSB argues that we want to target customers for whom the company would lose the most money if they left. The expected benefit of targeting is:</p>
<p><span class="math display">\[EB_T(x) = p(S|x,T)*(u_s(x)-c)+[1-p(S|x,T)]*(u_{NS}(x)-c)\]</span></p>
<p>In words: The expected benefit of targeting a customer is equal to:</p>
<ol style="list-style-type: decimal">
<li>The probability a customer will stay if targeted multiplied by the profit if she stays (minus the incentive)</li>
</ol>
<p><em>plus</em></p>
<ol start="2" style="list-style-type: decimal">
<li>The probability she will leave if targeted multiplied by the profit if she leaves (minus the incentive).</li>
</ol>
<p>Intuitively, if we hold profit constant across customers, then the benefit of targeting will be controlled by <span class="math inline">\(p(S|x,T)\)</span>, the probability of staying if targeted, since as that probability goes up so does the expected benefit. (The second term in the equation, <span class="math inline">\([1-p(S|x,T)]*(u_{NS}(x)-c)\)</span>, will tend to go to 0 since the profit due to not staying, <span class="math inline">\(u_{NS}\)</span>, will be 0.)</p>
<p>And the expected benefit of <em>not</em> targeting is:</p>
<p><span class="math display">\[EB_{notT}(x) = p(S|x,notT)*(u_s(x)-c)+[1-p(S|x,notT)]*(u_{NS}(x)-c)\]</span></p>
<p>This has a similar interpretation to the equation above for <span class="math inline">\(EB_T\)</span>.</p>
<p>The point of these complicated formulations is to figure out which customers will be most profitable to target. We need to identify those customers for whom the Value of Targeting (or VT) = <span class="math inline">\(EB_T(x) - EB_{notT}(x)\)</span> is largest. These are the customers whose probability of staying will be most impacted by the intervention and whom it will be most profitable to target: rather than leaving they stay and continue paying fees. (By contrast, a customer who was already going to stay will not be profitable to target.) DSB expresses this result as: <span class="math inline">\(VT=\Delta(p)*u_S(x)-c\)</span>, the change in the probability of staying multiplied by profitability minus the cost of the incentive.</p>
<p>In some respects this is an unsatisfying result because: (a) we don’t know what the future profit of customers will be (some might stay a year, others 10 years, with differing contract values), and (b) we don’t know how responsive individual customers would be to an incentive. Nevertheless, these formulations have helped us decompose, and thereby better understand, the business problem and to think harder about data requirements. Part of the report we write could include a summary of which additional data items would be required to improve model quality and the profitability of future marketing campaigns.</p>
</div>
<div id="section-what-next" class="section level2">
<h2>What Next?</h2>
<p>As DSB says, “Business exigencies may force us to proceed. We need to reduce churn; marketing has confidence in this offer, and we certainly have some data that might inform how we proceed” (287). How shall we proceed?</p>
<p>We can make some simplifying assumptions:</p>
<ol style="list-style-type: decimal">
<li><p>The future profit for all retained customers will be the same.</p></li>
<li><p>The cost of the incentive for all customers will be the same.</p></li>
<li><p>The customers who get the incentive will stay.</p></li>
</ol>
<p>These assumptions reduce the expected benefit formulation to the problem of estimating <span class="math inline">\(\Delta(p)\)</span>. Intuitively, we can see that customers who are already likely to stay—large model-estimated <span class="math inline">\(p(STAY)\)</span>— will have correspondingly small potential <span class="math inline">\(\Delta(p)\)</span> since their retention behavior can’t change much: they were already very likely to stay.</p>
<p>Consequently, this analysis suggests that Marketing should focus on those customers with the highest probability of leaving since, in the absence of further information, they offer the largest potential <span class="math inline">\(\Delta(p)\)</span>. The prescriptive analytics part of the project could consist in providing recommendations to Marketing regarding which customers to contact and how to structure the incentive.</p>
</div>
<div id="section-which-customers-to-contact" class="section level2">
<h2>Which Customers to Contact?</h2>
<p>The tree model can be used to produce a ranked contact list of customers. The ranking would essentially provide guidance on how to spend the incentive money allocated for the campaign: spend it on the customers near the top of the list. To produce the list, simply add the estimate of <span class="math inline">\(p(LEAVE|X)\)</span> into the original data frame and sort on that variable, known as a “score,” selecting the resulting column along with <code>id</code>. Here is example code:</p>
<div class="tutorial-exercise" data-label="contact" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>d %&gt;%
  mutate(probability = predict(tree_model, type = &quot;prob&quot;)[,1]) %&gt;%
  arrange(desc(probability)) %&gt;%
  select(id, probability) </code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>The list is organized by the idea that some customers should be targeted—those with a high probability of leaving—and some should not be targeted. But <em>how many</em> from the list should be targeted? That is a key question, and one you should expect to be asked when you present your plan to Marketing.</p>
</div>
<div id="section-how-many-customers-to-contact" class="section level2">
<h2>How Many Customers to Contact?</h2>
<p>As we saw above, a profit curve can be used to estimate the proportion of customers who should be contacted. We have stipulated that everyone who is targeted will be retained, hence <span class="math inline">\(p(S|x,T)\)</span> = 1. Customers who were correctly predicted to leave (true positives) and were targeted, converting them from <code>LEAVE</code> to <code>STAY</code>, would thus generate 600 dollars in revenue. Customers who were incorrectly predicted to leave (false positives) and were targeted would generate -200 dollars in revenue. Customers who were predicted to stay would not be offered the incentive, and, generating no costs or revenue, can be ignored for evaluating profit.</p>
<p>The code for a profit curve is tricky to understand, so let’s display and explain the underlying data first.</p>
<div class="tutorial-exercise" data-label="data" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Define revenue and cost
revenue &lt;- 800
cost &lt;- 200

# Underlying data
d %&gt;%
  mutate(probability = predict(tree_model, type = &quot;prob&quot;)[,1]) %&gt;%
  arrange(desc(probability)) %&gt;%
  mutate(profit = ifelse(leave == &quot;LEAVE&quot;, revenue - cost, -cost),
         cum_profit = cumsum(profit),
         customers = 1:n() / n()) %&gt;%
  select(probability, profit, cum_profit, customers) </code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Here are the steps:</p>
<ol style="list-style-type: decimal">
<li>Add predicted probability of leaving, <span class="math inline">\(p(LEAVE)\)</span>, to the data.</li>
<li>Important: as in the contact list, the data must be sorted by <span class="math inline">\(p(LEAVE)\)</span>, high to low.</li>
<li>Calculate a cumulative or running proportion, <code>customers</code>, for each row. Rows 1-10, for example, represent .002 of the dataset. This will be the x-axis in the profit curve.</li>
<li>Calculate <code>profit</code>. 600 dollars if the observed outcome for a row is <code>LEAVE</code>, or -200 dollars if <code>STAY</code>.</li>
<li>Calculate <code>cum_profit</code>, a cumulative tally of <code>profit</code>. This will be the y-axis in the profit curve.</li>
</ol>
<p>Imagine that we are using the probability in each row as the threshold for predicting <code>LEAVE</code> such that we predict <code>LEAVE</code> for the rows above and inclusive of that row. In row 5, for example, we predict <code>LEAVE</code> for just 5 rows (1 - 5), <code>STAY</code> for all the others (6 - 4994), while in row 6 we predict <code>LEAVE</code> for 6 rows (1 - 6), <code>STAY</code> for all the others (7 - 4994), and so on. In effect, we are successively subsetting the data by rows—selecting those customers predicted to leave—and computing a profit summary for the subset, contained in the final value of the subset’s <code>cum_profit</code>. For example, in the subset consisting in the first 10 rows there were 9 true positives and 1 false positive, so subsetting the data at row 10 would produce combined profit of 10 x 600 - 200 = 5200, which is the value of <code>cum_profit</code> for row 10.</p>
<p>Here is the plot.</p>
<div class="tutorial-exercise" data-label="plot" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Define revenue and cost
revenue &lt;- 800
cost &lt;- 200

# Make plot
d %&gt;%
  mutate(probability = predict(tree_model, type = &quot;prob&quot;)[,1]) %&gt;%
  arrange(desc(probability)) %&gt;%
  mutate(profit = ifelse(leave == &quot;LEAVE&quot;, revenue - cost, -cost),
         cum_profit = cumsum(profit),
         customers = 1:n() / n()) %&gt;%
  ggplot(aes(customers, cum_profit))+
  geom_line() +
  labs(title = &quot;Profit Curve for Marketing Campaign&quot;,
       x = &quot;Proportion of customers targeted (decreasing by score)&quot;,
       y = &quot;Profit&quot;) +
  theme_minimal()</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<!-- ```{r} -->
<!-- # Define revenue and cost -->
<!-- revenue <- 800 -->
<!-- cost <- -200 -->
<!-- # Make plot -->
<!-- d %>% -->
<!--   mutate(probability = predict(tree_model, type = "prob")[,1]) %>% -->
<!--   arrange(desc(probability)) %>% -->
<!--   mutate(predicted= 1:n(), -->
<!--          observed = ifelse(leave == "LEAVE", 1, 0), -->
<!--          TP = cumsum(observed), -->
<!--          FP = predicted - TP, -->
<!--          profit = TP * revenue + FP * cost, -->
<!--          customers = 1:n() / n()) %>%  -->
<!--   ggplot(aes(customers, profit))+ -->
<!--   geom_line() + -->
<!--   labs(title = "Profit Curve for Marketing Campaign", -->
<!--        x = "Proportion of customers targeted (decreasing by score)", -->
<!--        y = "Profit") + -->
<!--   theme_minimal() -->
<!-- ``` -->
<p>The plot reveals what proportion of customers should be targeted in order to maximize profit. When the targeted group increasingly includes customers with a low probability of leaving, the costs will begin to overwhelm the profits and the campaign will have diminishing returns. That happens at about .75 in the plot.</p>
<p>In sum, this profit curve illustrates that you can be confident in your recommendation to Marketing that profit would be maximized by contacting approximately the top 75% of customers (ranked by the probability of leaving). Moreover, if the budget for the campaign is limited (and budgets are always limited), then contacting just 50% of the customers, for example, would reap nearly the same additional profit.</p>
</div>
<div id="section-how-to-structure-the-incentive" class="section level2">
<h2>How to structure the incentive?</h2>
<p>Of course, one of our initial assumptions is dubious: not everyone who receives the special offer will respond by renewing the contract. Therefore, we should think about how to structure the incentive to make it as appealing as possible to customers likely to churn. To this end variable importance from the tree model can provide helpful guidance. Why are customers leaving? We saw from EDA, as well as from the tree model, that customer satisfaction had very little impact on customer churn. What about the other predictors that showed a large impact?</p>
<pre class="r"><code>tree_model$variable.importance</code></pre>
<pre><code>##                     overage                       house 
##                  174.275698                  170.430087 
## over_15mins_calls_per_month                      income 
##                  134.093539                  120.389006 
##               handset_price                    leftover 
##                   99.044207                   80.498682 
##       average_call_duration        reported_usage_level 
##                   66.095350                    1.713191 
##  considering_change_of_plan 
##                    1.265890</code></pre>
<p><code>Overage</code> is interesting. By definition, <code>overage</code> is a penalty charge, and it would seem to be a pain point for some customers. The company could potentially adjust or waive the penalty. Let’s visualize the relationship between overage and the probability of leaving, first adding the model estimated probability into the data frame:</p>
<pre class="r"><code>#  Add the probability of leaving
d %&gt;%
  mutate(p = predict(tree_model, type = &quot;prob&quot;)[,1]) %&gt;% 
  ggplot(aes(overage, p)) +
  geom_jitter() +
  labs(title = &quot;p(LEAVE) ~ overage&quot;) +
  theme_minimal()</code></pre>
<p><img src="Model_Evaluation_and_Deployment_files/figure-html/unnamed-chunk-8-1.png" width="624" /></p>
<p>High overage seems to affect the probability of leaving for some customers but not others. Perhaps a third variable accounts for the difference, such as other high importance variables: <code>house</code>, <code>income</code>, high usage (<code>over_15mins_calls_per_month</code>). For ease of visualization we need to bin these continuous variables. <code>dplyr</code> has a very handy function, <code>cut_number()</code>, that bins continuous variables into categories with equal numbers of observations. Our strategy will be to create small multiples plots to see whether the relationship between <code>overage</code> and <span class="math inline">\(p(LEAVE)\)</span> varies by levels of <code>house</code>, <code>income</code>, high usage.</p>
<pre class="r"><code># Add categorical variables
d %&lt;&gt;% #This is an assignment operator from magrittr package, same as:  d &lt;- d %&gt;%
  mutate(income_cat = cut_number(income/1000, 4),
         house_cat = cut_number(house/100000,4),
         usage = cut_number(over_15mins_calls_per_month, 4))

glimpse(d)</code></pre>
<pre><code>## Observations: 4,994
## Variables: 16
## $ college                     &lt;fct&gt; yes, no, no, yes, no, no, yes, yes, …
## $ income                      &lt;dbl&gt; 23859, 72466, 30883, 44512, 70535, 1…
## $ overage                     &lt;dbl&gt; 70, 67, 60, 0, 0, 0, 79, 0, 0, 0, 22…
## $ leftover                    &lt;dbl&gt; 0, 16, 0, 22, 0, 56, 24, 0, 0, 74, 1…
## $ house                       &lt;dbl&gt; 519105, 271182, 647281, 754958, 6534…
## $ handset_price               &lt;dbl&gt; 154, 262, 211, 232, 310, 778, 365, 2…
## $ over_15mins_calls_per_month &lt;dbl&gt; 5, 5, 3, 0, 0, 5, 5, 5, 1, 0, 10, 3,…
## $ average_call_duration       &lt;dbl&gt; 8, 5, 8, 5, 14, 1, 6, 10, 8, 2, 1, 5…
## $ reported_satisfaction       &lt;ord&gt; unsat, unsat, unsat, unsat, very_uns…
## $ reported_usage_level        &lt;ord&gt; little, little, little, little, litt…
## $ considering_change_of_plan  &lt;ord&gt; actively_looking_into_it, actively_l…
## $ leave                       &lt;fct&gt; LEAVE, LEAVE, STAY, LEAVE, STAY, STA…
## $ id                          &lt;dbl&gt; 8183, 12501, 7425, 13488, 11389, 146…
## $ income_cat                  &lt;fct&gt; &quot;[20,41.6]&quot;, &quot;(41.6,75]&quot;, &quot;[20,41.6]…
## $ house_cat                   &lt;fct&gt; &quot;(4.52,7.02]&quot;, &quot;(2.61,4.52]&quot;, &quot;(4.52…
## $ usage                       &lt;fct&gt; &quot;(4,14]&quot;, &quot;(4,14]&quot;, &quot;(1,4]&quot;, &quot;[0,1]&quot;…</code></pre>
<p>Notice that <code>cut_number()</code> has created a factor variable that indicates the numeric range of the bin. We will start by analyzing high usage.</p>
<pre class="r"><code>d %&gt;%
  mutate(p = predict(tree_model, type = &quot;prob&quot;)[,1]) %&gt;% 
  ggplot(aes(overage, p)) +
  geom_jitter() +
  facet_wrap(~usage) +
  labs(title = &quot;p(LEAVE) ~ overage, varying by usage&quot;)</code></pre>
<p><img src="Model_Evaluation_and_Deployment_files/figure-html/unnamed-chunk-10-1.png" width="624" /></p>
<p>Not much here. The basic shape of the relationship between <code>overage</code> and <span class="math inline">\(p(LEAVE)\)</span> does not change across levels of high usage.</p>
<pre class="r"><code>d %&gt;%
  mutate(p = predict(tree_model, type = &quot;prob&quot;)[,1]) %&gt;% 
  ggplot(aes(overage, p)) +
  geom_jitter() +
  facet_wrap(~house_cat) +
  labs(title = &quot;p(LEAVE) ~ overage, varying by house&quot;)</code></pre>
<p><img src="Model_Evaluation_and_Deployment_files/figure-html/unnamed-chunk-11-1.png" width="624" /></p>
<p>This is more promising. We can see that the relationship between <code>overage</code> and <span class="math inline">\(p(LEAVE)\)</span> does depend on house value, such that at lower values of <code>house</code> high <code>overage</code> is perfectly associated with high probabilities of leaving. What about <code>income</code>?</p>
<pre class="r"><code>d %&gt;%
  mutate(p = predict(tree_model, type = &quot;prob&quot;)[,1]) %&gt;% 
  ggplot(aes(overage, p)) +
  geom_jitter() +
  facet_wrap(~income_cat) +
  labs(title = &quot;p(LEAVE) ~ overage, varying by income&quot;)</code></pre>
<p><img src="Model_Evaluation_and_Deployment_files/figure-html/unnamed-chunk-12-1.png" width="624" /></p>
<p>Likewise for <code>income</code>: there is a high probability of leaving at high levels of <code>income</code> and high levels of <code>overage</code>. What about <code>house</code> and <code>income</code> together?</p>
<pre class="r"><code>d %&gt;%
  mutate(p = predict(tree_model, type = &quot;prob&quot;)[,1]) %&gt;% 
  ggplot(aes(overage, p)) +
  geom_jitter() +
  facet_grid(house_cat~income_cat) +
  labs(title = &quot;p(LEAVE) ~ overage, varying by income and house&quot;)</code></pre>
<p><img src="Model_Evaluation_and_Deployment_files/figure-html/unnamed-chunk-13-1.png" width="624" /></p>
<p>Here we can see that <code>house</code>, <code>income</code>, and <code>overage</code> together reveal structure in the probability of leaving. In general, customers with high levels of <code>overage</code> have a high probability of leaving. These customers could be targeted in a marketing campaign with an incentive structure around reducing or eliminating the penalty. There are exceptions, however, so we can be even more specific. The marketing campaign should target customers who:</p>
<ol style="list-style-type: decimal">
<li>Have over $100 in overage fees per month living in homes of below average value.</li>
<li>Have over $100 in overage fees per month living in homes of above average value, who are in the highest quartile of income.</li>
</ol>
<p>Let’s use these rules to identify customers to target with an incentive designed around <code>overage</code>:</p>
<pre class="r"><code>d %&lt;&gt;%
  mutate(p = predict(tree_model, type = &quot;prob&quot;)[,1],
         p = round(p, 2),
         target = ifelse((p &gt; .75 &amp; house/100000 &lt; 4.53) |
                        (p &gt; .75 &amp; house/100000 &gt; 4.53 &amp; income/1000 &gt; 115), &quot;yes&quot;, &quot;no&quot;))

table(target = d$target, `probability of leaving` = d$p)</code></pre>
<pre><code>##       probability of leaving
## target 0.18 0.31 0.39 0.53 0.62 0.74  0.8
##    no  1118  756  271  733  743  299  193
##    yes    0    0    0    0    0    0  881</code></pre>
<p>You could recommend that for these 881 customers Marketing should design a customized incentive centered on <code>overage.</code></p>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
library(knitr)
library(tidyverse)
library(magrittr)
knitr::opts_chunk$set(echo = FALSE)

</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-predict-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-predict-code-editor`)), session)
output$`tutorial-exercise-predict-output` <- renderUI({
  `tutorial-exercise-predict-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-predict-prob1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-predict-prob1-code-editor`)), session)
output$`tutorial-exercise-predict-prob1-output` <- renderUI({
  `tutorial-exercise-predict-prob1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-tab-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-tab-code-editor`)), session)
output$`tutorial-exercise-tab-output` <- renderUI({
  `tutorial-exercise-tab-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-tab2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-tab2-code-editor`)), session)
output$`tutorial-exercise-tab2-output` <- renderUI({
  `tutorial-exercise-tab2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-tab3-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-tab3-code-editor`)), session)
output$`tutorial-exercise-tab3-output` <- renderUI({
  `tutorial-exercise-tab3-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-contact-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-contact-code-editor`)), session)
output$`tutorial-exercise-contact-output` <- renderUI({
  `tutorial-exercise-contact-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-data-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-data-code-editor`)), session)
output$`tutorial-exercise-data-output` <- renderUI({
  `tutorial-exercise-data-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-plot-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-plot-code-editor`)), session)
output$`tutorial-exercise-plot-output` <- renderUI({
  `tutorial-exercise-plot-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.13"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["localforage"]},{"type":"character","attributes":{},"value":["1.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/localforage"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["localforage.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","broom","cellranger","cli","colorspace","compiler","crayon","datasets","digest","dplyr","evaluate","fansi","forcats","generics","ggplot2","glue","graphics","grDevices","grid","gtable","haven","hms","htmltools","htmlwidgets","httpuv","httr","janitor","jsonlite","knitr","labeling","later","lattice","lazyeval","learnr","lubridate","magrittr","markdown","methods","mime","modelr","munsell","nlme","pillar","pkgconfig","plyr","promises","purrr","R6","Rcpp","readr","readxl","reshape2","rlang","rmarkdown","rpart","rpart.plot","rprojroot","rstudioapi","rvest","scales","shiny","snakecase","stats","stringi","stringr","tibble","tidyr","tidyselect","tidyverse","tools","utf8","utils","vctrs","withr","xfun","xml2","xtable","yaml","zeallot"]},{"type":"character","attributes":{},"value":["0.2.1","1.1.4","3.6.0","0.5.2","1.1.0","1.1.0","1.4-1","3.6.0","1.3.4","3.6.0","0.6.19","0.8.1","0.14","0.4.0","0.4.0","0.0.2","3.2.0","1.3.1","3.6.0","3.6.0","3.6.0","0.3.0","2.1.0","0.4.2","0.3.6","1.3","1.5.1","1.4.0","1.2.0","1.6","1.23","0.3","0.8.0","0.20-38","0.2.2","0.9.2.1","1.7.4","1.5","1.0","3.6.0","0.7","0.1.4","0.5.0","3.1-139","1.4.1","2.0.2","1.8.4","1.0.1","0.3.2","2.4.0","1.0.1","1.3.1","1.3.1","1.4.3","0.3.4","1.13","4.1-15","3.0.7","1.3-2","0.10","0.3.4","1.0.0","1.3.2","0.11.0","3.6.0","1.4.3","1.4.0","2.1.3","0.8.3","0.2.5","1.2.1","3.6.0","1.1.4","3.6.0","0.1.0","2.1.2","0.7","1.2.0","1.8-4","2.2.0","0.1.0"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Tutorial: Model Evaluation and Deployment</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>

</html>
